//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fastener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fastener.Properties.MessageLocalization", typeof(MessageLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sono presenti attività non associate ad un rapportino.
        /// </summary>
        internal static string activity_act_with_no_report {
            get {
                return ResourceManager.GetString("activity_act_with_no_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICA.
        /// </summary>
        internal static string activity_button_modify {
            get {
                return ResourceManager.GetString("activity_button_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALVA.
        /// </summary>
        internal static string activity_button_save {
            get {
                return ResourceManager.GetString("activity_button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        internal static string activity_confirm {
            get {
                return ResourceManager.GetString("activity_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellazione attività selezionate.
        /// </summary>
        internal static string activity_confirm_bulk_delete {
            get {
                return ResourceManager.GetString("activity_confirm_bulk_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare tipologia manutenzione.
        /// </summary>
        internal static string activity_man_type_not_selected {
            get {
                return ResourceManager.GetString("activity_man_type_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attività in conflitto con altre attività inserite.
        /// </summary>
        internal static string activity_overlap {
            get {
                return ResourceManager.GetString("activity_overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generato rapportino numero: .
        /// </summary>
        internal static string activity_report_generated {
            get {
                return ResourceManager.GetString("activity_report_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ore delle attività selezionate sono maggiori di 12. Continuare a generare il Rapportino?.
        /// </summary>
        internal static string activity_report_many_hours_confirm {
            get {
                return ResourceManager.GetString("activity_report_many_hours_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ore delle attività selezionate sono troppe per la generazione di un singolo rapportino.
        /// </summary>
        internal static string activity_report_too_many_hours {
            get {
                return ResourceManager.GetString("activity_report_too_many_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istante di inizio e fine attività non congruenti.
        /// </summary>
        internal static string activity_ts_mismatch {
            get {
                return ResourceManager.GetString("activity_ts_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervallo orario non corretto. Verificare.
        /// </summary>
        internal static string activity_wrong_min_range {
            get {
                return ResourceManager.GetString("activity_wrong_min_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diritti insufficienti per creare un profilo super user.
        /// </summary>
        internal static string ana_cannot_create_superuser {
            get {
                return ResourceManager.GetString("ana_cannot_create_superuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare l&apos;evento.
        /// </summary>
        internal static string event_cannot_cancel {
            get {
                return ResourceManager.GetString("event_cannot_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; possibile copiare solo un evento.
        /// </summary>
        internal static string event_copy_too_many_rows {
            get {
                return ResourceManager.GetString("event_copy_too_many_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGGIUNGI EVENTO.
        /// </summary>
        internal static string event_save_button_text_insert {
            get {
                return ResourceManager.GetString("event_save_button_text_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICA EVENTO.
        /// </summary>
        internal static string event_save_button_text_modify {
            get {
                return ResourceManager.GetString("event_save_button_text_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentuale residua del driver non sufficiente.
        /// </summary>
        internal static string events_driver_perc_exceeds {
            get {
                return ResourceManager.GetString("events_driver_perc_exceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password non valida.
        /// </summary>
        internal static string fmrLogin_PasswordNonValida {
            get {
                return ResourceManager.GetString("fmrLogin_PasswordNonValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di connessione.
        /// </summary>
        internal static string frmLogin_Connessione {
            get {
                return ResourceManager.GetString("frmLogin_Connessione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string frmLogin_Errore {
            get {
                return ResourceManager.GetString("frmLogin_Errore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore caricamento utente.
        /// </summary>
        internal static string frmLogin_ErroreCaricamenteUtente {
            get {
                return ResourceManager.GetString("frmLogin_ErroreCaricamenteUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non trovato.
        /// </summary>
        internal static string frmLogin_UtenteNonTrovato {
            get {
                return ResourceManager.GetString("frmLogin_UtenteNonTrovato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password troppo corta.
        /// </summary>
        internal static string frmPass_PasswordCorta {
            get {
                return ResourceManager.GetString("frmPass_PasswordCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password non corrispondente.
        /// </summary>
        internal static string frmPass_PasswordNonCorrispondente {
            get {
                return ResourceManager.GetString("frmPass_PasswordNonCorrispondente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password OK.
        /// </summary>
        internal static string frmPass_PasswordOK {
            get {
                return ResourceManager.GetString("frmPass_PasswordOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        internal static string man_plant_confirm {
            get {
                return ResourceManager.GetString("man_plant_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare aree selezionate ?.
        /// </summary>
        internal static string man_plant_delete_are {
            get {
                return ResourceManager.GetString("man_plant_delete_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare CA selezionate?.
        /// </summary>
        internal static string man_plant_delete_CA {
            get {
                return ResourceManager.GetString("man_plant_delete_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare i componenti selezionati ?.
        /// </summary>
        internal static string man_plant_delete_com {
            get {
                return ResourceManager.GetString("man_plant_delete_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare gli impianti selezionati ?.
        /// </summary>
        internal static string man_plant_delete_imp {
            get {
                return ResourceManager.GetString("man_plant_delete_imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare le macchine selezionate ?.
        /// </summary>
        internal static string man_plant_delete_mac {
            get {
                return ResourceManager.GetString("man_plant_delete_mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare schede selezionate?.
        /// </summary>
        internal static string man_plant_delete_scheda {
            get {
                return ResourceManager.GetString("man_plant_delete_scheda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellare i sottocomponenti selezionati ?.
        /// </summary>
        internal static string man_plant_delete_scm {
            get {
                return ResourceManager.GetString("man_plant_delete_scm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si desidera uscire anche se sono presenti attività pendenti ?.
        /// </summary>
        internal static string quit_even_if_act_no_report {
            get {
                return ResourceManager.GetString("quit_even_if_act_no_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo rapportino è già stato inviato. Si desidera re-inviare il rapportino N. .
        /// </summary>
        internal static string reports_resend {
            get {
                return ResourceManager.GetString("reports_resend", resourceCulture);
            }
        }
    }
}
